apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kourier-ingress
  namespace: kourier-system
spec:
  rules:
  - http:
     paths:
       - path: /
         backend:
           serviceName: kourier
           servicePort: 80

